# 1
# sever
# - 在 application.yml 的优先级没有 application.properties 高
# - 所以: 端口是 8080 生效，而不是 8081
server:
  port: 9999


# ------- ------- ------- ------- ------- ------- -------
# ------- ------- ------- ------- ------- ------- -------
# 2
spring:
  # 2.1
  # jackson
  # - globally format data through jackson.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 2.2
  # redis
  redis:
    host: localhost
    port: 6379
    password: rootroot

  # 2.3
  mvc:
    static-path-pattern: "/resources/**"

  # 2.4
  datasource:
    # 1. 只要装了 ( mysql驱动 ) 和 ( jdbc数据库连接池 )，并且在这里配置好 ( 数据库连接池相关的配置项 ) 就能连接数据库
    # 2. mysql驱动 => mysql-connector-java
    # 3. jdbc连接池 => spring-boot-starter-jdbc
    # 4. 更进一步：还可以使用 ( Druid数据源 + MyBatis )
#    url: jdbc:mysql://localhost:3306/personal_music?serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: rootroot
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_music?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
#  jpa:
##    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    database: mysql
#    show-sql: true
#    jdbc:
#      template:
#        query-timeout: 10 # 10s没查出来就超时

# 日志
#logging:
#  level:
#    org.springframework.boot.autoconfigure: DEBUG