# 1
# sever
# - 在 application.yml 的优先级没有 application.properties 高
# - 所以: 端口是 8080 生效，而不是 8081
server:
  port: 8081


# ------- ------- ------- ------- ------- ------- -------
# ------- ------- ------- ------- ------- ------- -------
# 2
spring:
  # 2.1
  # jackson
  # - globally format data through jackson.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 2.2
  # redis
  redis:
    host: localhost
    port: 6379
    password: rootroot

  # 2.3
  mvc:
    static-path-pattern: "/resources/**"