# 1
# sever
# - 在 application.yml 的优先级没有 application.properties 高
# - 所以: 端口是 8080 生效，而不是 8081
server:
  port: 9999


# ------- ------- ------- ------- ------- ------- -------
# ------- ------- ------- ------- ------- ------- -------
# 2
spring:

  # 2.1
  # jackson
  # - globally format data through jackson.
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 2.2
  # redis
  redis:
    host: localhost
    port: 6379
    password: rootroot

  # 2.3
  mvc:
    static-path-pattern: "/resources/**"

  # 2.4
  datasource:
    # 1. 只要装了 ( mysql驱动 ) 和 ( jdbc数据库连接池 )，并且在这里配置好 ( 数据库连接池相关的配置项 ) 就能连接数据库
    # 2. mysql驱动 => mysql-connector-java
    # 3. jdbc连接池 => spring-boot-starter-jdbc
    # 4. 更进一步：还可以使用 ( Druid数据源 + MyBatis )
    url: jdbc:mysql://localhost:3306/personal_music?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot

  # 2.5
  # show-sql: true 表示开启sql语句日志
  # hibernate.ddl-auto: update; 没有数据库时自动创建 [ hibernate:冬眠 n ]
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true